joint1_position:
  type: position_controllers/JointPositionController
  joint: id_11

joint2_position:
  type: position_controllers/JointPositionController
  joint: id_12

joint3_position:
  type: position_controllers/JointPositionController
  joint: id_13

joint4_position:
  type: position_controllers/JointPositionController
  joint: id_14
