joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm:
    type: position_controllers/JointTrajectoryController
    joints:
        - id_11
        - id_12
        - id_13
        - id_14

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        id_11: {trajectory: 0.1, goal: 0.1}
        id_12: {trajectory: 0.1, goal: 0.1}
        id_13: {trajectory: 0.1, goal: 0.1}
        id_14: {trajectory: 0.1, goal: 0.1}


    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

gripper:
    type: position_controllers/JointTrajectoryController
    joints:
        - id_15
        - gripper_sub

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        id_15: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10