controller_list:
  - name: fake_openmanipulator_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    joints:
      - gripper
initial:  # Define initial robot poses.
  - group: openmanipulator_arm
    pose: arm_zero
  - group: gripper
    pose: gripper_open